/// @desc Declare all Weapons

// Empty
weapons[0] = ds_map_create();
ds_map_add(weapons[0], "weapon", "none");
ds_map_add(weapons[0], "atk_type", "none");
ds_map_add(weapons[0], "hands", 0);
ds_map_add(weapons[0], "hand_one", [0, 0]);
ds_map_add(weapons[0], "hand_two", [0, 0]);
ds_map_add(weapons[0], "offset_x", 0);
ds_map_add(weapons[0], "offset_y", 0);
ds_map_add(weapons[0], "min_damage", 0);
ds_map_add(weapons[0], "max_damage", 0);
ds_map_add(weapons[0], "bullet_speed", 0);
ds_map_add(weapons[0], "bullet_speed_var", 0);
ds_map_add(weapons[0], "decay", 0);
ds_map_add(weapons[0], "reload", 0);
ds_map_add(weapons[0], "burst", 0);
ds_map_add(weapons[0], "bullets", 0);
ds_map_add(weapons[0], "base_accuracy", 0);
ds_map_add(weapons[0], "recoil", 0);
ds_map_add(weapons[0], "max_recoil", 0);
ds_map_add(weapons[0], "recoil_mult", 0);
ds_map_add(weapons[0], "shake_dur", 0);
ds_map_add(weapons[0], "max_ammo", 0);

// 1911
weapons[1] = ds_map_create();
ds_map_add(weapons[1], "weapon", "1911");
ds_map_add(weapons[1], "atk_type", "semi_auto");
ds_map_add(weapons[1], "hands", 1);
ds_map_add(weapons[1], "hand_one", [-3, 7]);
ds_map_add(weapons[1], "hand_two", [0, 0]);
ds_map_add(weapons[1], "offset_x", -4);
ds_map_add(weapons[0], "offset_y", 0);
ds_map_add(weapons[1], "min_damage", 48);
ds_map_add(weapons[1], "max_damage", 52);
ds_map_add(weapons[1], "bullet_speed", 20);
ds_map_add(weapons[1], "bullet_speed_var", 1);
ds_map_add(weapons[1], "decay", 0.5);
ds_map_add(weapons[1], "reload", 10);
ds_map_add(weapons[1], "burst", 1);
ds_map_add(weapons[1], "bullets", 1);
ds_map_add(weapons[1], "base_accuracy", 2);
ds_map_add(weapons[1], "recoil", 2);
ds_map_add(weapons[1], "max_recoil", 6);
ds_map_add(weapons[1], "recoil_mult", 3);
ds_map_add(weapons[1], "shake_dur", 8);
ds_map_add(weapons[1], "max_ammo", 7);

// Glock 17
weapons[2] = ds_map_create();
ds_map_add(weapons[2], "weapon", "glock");
ds_map_add(weapons[2], "atk_type", "semi_auto");
ds_map_add(weapons[2], "hands", 1);
ds_map_add(weapons[2], "hand_one", [0, 0]);
ds_map_add(weapons[2], "hand_two", [0, 0]);
ds_map_add(weapons[2], "offset", 0);
ds_map_add(weapons[2], "min_damage", 18);
ds_map_add(weapons[2], "max_damage", 22);
ds_map_add(weapons[2], "bullet_speed", 21);
ds_map_add(weapons[2], "bullet_speed_var", 1);
ds_map_add(weapons[2], "decay", 0.5);
ds_map_add(weapons[2], "reload", 3);
ds_map_add(weapons[2], "burst", 1);
ds_map_add(weapons[2], "bullets", 1);
ds_map_add(weapons[2], "base_accuracy", 2.5);
ds_map_add(weapons[2], "recoil", 2.5);
ds_map_add(weapons[2], "max_recoil", 7.5);
ds_map_add(weapons[2], "recoil_mult", 1.5);
ds_map_add(weapons[2], "shake_dur", 7);
ds_map_add(weapons[2], "max_ammo", 17);

// Uzi
weapons[3] = ds_map_create();
ds_map_add(weapons[3], "weapon", "Uzi");
ds_map_add(weapons[3], "atk_type", "auto");
ds_map_add(weapons[3], "hands", 1);
ds_map_add(weapons[3], "hand_one", [0, 0]);
ds_map_add(weapons[3], "hand_two", [0, 0]);
ds_map_add(weapons[3], "offset", 0);
ds_map_add(weapons[3], "min_damage", 19);
ds_map_add(weapons[3], "max_damage", 23);
ds_map_add(weapons[3], "bullet_speed", 23);
ds_map_add(weapons[3], "bullet_speed_var", 1);
ds_map_add(weapons[3], "decay", 1.5);
ds_map_add(weapons[3], "reload", 6);
ds_map_add(weapons[3], "burst", 1);
ds_map_add(weapons[3], "bullets", 1);
ds_map_add(weapons[3], "base_accuracy", 3);
ds_map_add(weapons[3], "recoil", 2);
ds_map_add(weapons[3], "max_recoil", 8);
ds_map_add(weapons[3], "recoil_mult", 1);
ds_map_add(weapons[3], "shake_dur", 6);
ds_map_add(weapons[3], "max_ammo", 32);

//Ak-47
weapons[4] = ds_map_create();
ds_map_add(weapons[4], "weapon", "AK-47");
ds_map_add(weapons[4], "atk_type", "semi_auto");
ds_map_add(weapons[4], "hands", 2);
ds_map_add(weapons[4], "hand_one", [0, 0]);
ds_map_add(weapons[4], "hand_two", [17, -3]);
ds_map_add(weapons[4], "offset", 0);
ds_map_add(weapons[4], "min_damage", 19);
ds_map_add(weapons[4], "max_damage", 25);
ds_map_add(weapons[4], "bullet_speed", 22);
ds_map_add(weapons[4], "bullet_speed_var", 1);
ds_map_add(weapons[4], "decay", 3);
ds_map_add(weapons[4], "reload", 6);
ds_map_add(weapons[4], "burst", 1);
ds_map_add(weapons[4], "bullets", 1);
ds_map_add(weapons[4], "base_accuracy", 2);
ds_map_add(weapons[4], "recoil", 0.3);
ds_map_add(weapons[4], "max_recoil", 7);
ds_map_add(weapons[4], "recoil_mult", 0.75);
ds_map_add(weapons[4], "shake_dur", 5);
ds_map_add(weapons[4], "max_ammo", 30);

//M4
weapons[5] = ds_map_create();
ds_map_add(weapons[5], "weapon", "M4");
ds_map_add(weapons[5], "atk_type", "semi_auto");
ds_map_add(weapons[5], "hands", 2);
ds_map_add(weapons[5], "hand_one", [0, 0]);
ds_map_add(weapons[5], "hand_two", [17, -2]);
ds_map_add(weapons[5], "offset", 0);
ds_map_add(weapons[5], "min_damage", 14);
ds_map_add(weapons[5], "max_damage", 22);
ds_map_add(weapons[5], "bullet_speed", 24);
ds_map_add(weapons[5], "bullet_speed_var", 1);
ds_map_add(weapons[5], "decay", 3);
ds_map_add(weapons[5], "reload", 5);
ds_map_add(weapons[5], "burst", 1);
ds_map_add(weapons[5], "bullets", 1);
ds_map_add(weapons[5], "base_accuracy", 2.5);
ds_map_add(weapons[5], "recoil", 0.2);
ds_map_add(weapons[5], "max_recoil", 7.5);
ds_map_add(weapons[5], "recoil_mult", 0.75);
ds_map_add(weapons[5], "shake_dur", 5);
ds_map_add(weapons[5], "max_ammo", 30);

//P90
weapons[6] = ds_map_create();
ds_map_add(weapons[6], "weapon", "P90");
ds_map_add(weapons[6], "atk_type", "semi_auto");
ds_map_add(weapons[6], "hands", 2);
ds_map_add(weapons[6], "hand_one", [0, 0]);
ds_map_add(weapons[6], "hand_two", [8, 0]);
ds_map_add(weapons[6], "offset", 9);
ds_map_add(weapons[6], "min_damage", 9);
ds_map_add(weapons[6], "max_damage", 13);
ds_map_add(weapons[6], "bullet_speed", 25);
ds_map_add(weapons[6], "bullet_speed_var", 1);
ds_map_add(weapons[6], "decay", 1);
ds_map_add(weapons[6], "reload", 4);
ds_map_add(weapons[6], "burst", 1);
ds_map_add(weapons[6], "bullets", 1);
ds_map_add(weapons[6], "base_accuracy", 2);
ds_map_add(weapons[6], "recoil", 0.2);
ds_map_add(weapons[6], "max_recoil", 6);
ds_map_add(weapons[6], "recoil_mult", 0.75);
ds_map_add(weapons[6], "shake_dur", 5);
ds_map_add(weapons[6], "max_ammo", 50);

//Remington 870
weapons[7] = ds_map_create();
ds_map_add(weapons[7], "weapon", "remington_870");
ds_map_add(weapons[7], "atk_type", "semi_auto");
ds_map_add(weapons[7], "hands", 2);
ds_map_add(weapons[7], "hand_one", [0, 0]);
ds_map_add(weapons[7], "hand_two", [17, 0]);
ds_map_add(weapons[7], "offset", 0);
ds_map_add(weapons[7], "min_damage", 15);
ds_map_add(weapons[7], "max_damage", 35);
ds_map_add(weapons[7], "bullet_speed", 24);
ds_map_add(weapons[7], "bullet_speed_var", 2);
ds_map_add(weapons[7], "decay", 0.5);
ds_map_add(weapons[7], "reload", 30);
ds_map_add(weapons[7], "burst", 1);
ds_map_add(weapons[7], "bullets", 12);
ds_map_add(weapons[7], "base_accuracy", 10);
ds_map_add(weapons[7], "recoil", 3);
ds_map_add(weapons[7], "max_recoil", 16);
ds_map_add(weapons[7], "recoil_mult", 0.5);
ds_map_add(weapons[7], "shake_dur", 20);
ds_map_add(weapons[7], "max_ammo", 5);